### ISSUE TITLE
Recomendación para el futuro

### ISSUE THREAD

**Issue by CarlosGabrieLuna** [BUGR2487/Inventario#1]
que pedo chiki baby, para futuros proyectos crea el  **_.gitignore_** y agrega el _*.class_ para que no te agregue los **_.class_** al repo, así ahorrar espacio en los push y luego git hub no te tirará pedos de que esta pesado tu puje 👍

**Comment by BUGR2487** [comment]
Ok ok, ese es un buen consejo!

**Comment by CarlosGabrieLuna** [comment]
otra cosa, en una chance que tengas quita los códigos comentados porque hacen mucho bulto en tu código y es menos posible de entender, lo digo por los bloques que tienes comentados, si ya tienes el control de versionado en git no debería ser problema recuperar ese código, checa si puedes darte la tarea de dejarlo sin comentarios de bloques de código que ya no usas porque eso es una mala practica de la programación por el motivo de que no se entiende

**Comment by BUGR2487** [comment]
Simon eso ando checando :'v
