### ISSUE TITLE
Colores en JTable

### ISSUE THREAD

**Issue by BUGR2487** [BUGR2487/Inventario#3]
Existe una clase que se llama "Entradas" y en ese formulario esta agregado un JTable, el cual cada dos registros tiene que esta de un color diferente, por ejemplo: Primera fila: azul Segunda fila: azul Tercera fila: verde Cuarta fila: verde Quinta fila: azul Sexta fila: azul Septima fila: verde Octava fila: verde Tiene que existir una opcion para que pueda cambiar de dos en dos a de tres en tres, cuatro en cuatro, dependiendo de lo que necesite el usuario.

**Comment by CarlosGabrieLuna** [comment]
como se llama el JTable? es que no lo veo ni haciendo ctrl+F jajajaja 😅

**Comment by BUGR2487** [comment]
TblEntradas

**Comment by CarlosGabrieLuna** [comment]
Va ya lo ví jajaja es que estaba buscando en la clase entradas que mencionaste, mmmm lo ví pero creo que antes de meterle más empezaré por pulir el código para entender bien que onda, incluso ver si se puede acomodar por paquetes las clases porque si está desordenado todo

**Comment by CarlosGabrieLuna** [comment]
Ya quedo lo deje de momento en la rama *_rma-colores-JTable_* en el siguiente commit: bf0fcb68d4309fb36f90ee8c8cc3605a35a6188d 👍
